name: Deploy Laravel Application to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            cd /home/radius/fcin-crm-laravel-mysql &&
            git pull &&
            composer install &&
            php artisan migrate --force
            && php artisan config:cache
            && php artisan route:cache
            && php artisan view:cache &&
            php artisan optimize &&
            php artisan queue:restart
