name: Deploy with SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run sshpass commands
      uses: matheusvanzan/sshpass-action@v2
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.REMOTE_PORT }}
        user: ${{ secrets.SERVER_USER }}
        pass: ${{ secrets.SERVER_PASS }}
        run: |
          # Your deployment commands here
          cd /home/${{ secrets.SERVER_USER }}/Projects/fcin-crm-laravel-mysql &&
          git remote set-url origin git@github.com:mdshemul48/fcin-crm-laravel-mysql.git &&
          git pull origin main
