name: Deploy with SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Run sshpass commands
      run: |
        sshpass -p ${{ secrets.SERVER_PASS }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.REMOTE_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'cd /home/${{ secrets.SERVER_USER }}/Projects/fcin-crm-laravel-mysql && git remote set-url origin git@github.com:mdshemul48/fcin-crm-laravel-mysql.git && git pull origin main'
