name: Deploy with SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: List .ssh directory
      run: ls -al ~/.ssh && cat ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p $SERVER_PORT $SERVER_USER@$SERVER_IP << EOF
          cd /home/$SERVER_USER/Projects/fcin-crm-laravel-mysql &&
          git remote set-url origin git@github.com:mdshemul48/fcin-crm-laravel-mysql.git &&
          git pull origin main
        EOF
